
**Atividade aula 02**

In [0]:
import numpy as np
import pandas as pd

In [0]:
a,b=40,100
pesos = (b - a) * np.random.random_sample((50)) + a
#pesos=pesos.reshape(5)
pesos

array([64.10007314, 62.46085388, 75.2802222 , 69.35872151, 62.2894576 ,
       53.51565114, 61.23664945, 58.48716828, 97.89289028, 75.64583495,
       95.31889564, 48.66077529, 94.74559111, 50.13710089, 83.7472085 ,
       42.38587637, 87.88339403, 77.78268494, 84.15070378, 51.26879494,
       65.12751467, 63.05835619, 87.532883  , 82.87813804, 67.7568048 ,
       54.37228014, 50.85004065, 93.59000956, 75.31271919, 52.83155881,
       62.44592497, 53.86925896, 54.37250844, 77.27283341, 49.66200443,
       78.01710936, 56.31492514, 75.92975945, 89.71785515, 97.8158916 ,
       82.99364223, 89.91539143, 73.88396088, 76.70689465, 99.3672263 ,
       46.40460086, 64.85041859, 42.0734067 , 49.73642122, 93.21009718])

In [0]:
alturas=np.linspace(1.10,2.10,50)
#alturas=alturas.reshape(5,10)
alturas

array([1.1       , 1.12040816, 1.14081633, 1.16122449, 1.18163265,
       1.20204082, 1.22244898, 1.24285714, 1.26326531, 1.28367347,
       1.30408163, 1.3244898 , 1.34489796, 1.36530612, 1.38571429,
       1.40612245, 1.42653061, 1.44693878, 1.46734694, 1.4877551 ,
       1.50816327, 1.52857143, 1.54897959, 1.56938776, 1.58979592,
       1.61020408, 1.63061224, 1.65102041, 1.67142857, 1.69183673,
       1.7122449 , 1.73265306, 1.75306122, 1.77346939, 1.79387755,
       1.81428571, 1.83469388, 1.85510204, 1.8755102 , 1.89591837,
       1.91632653, 1.93673469, 1.95714286, 1.97755102, 1.99795918,
       2.01836735, 2.03877551, 2.05918367, 2.07959184, 2.1       ])

In [0]:
ps =pd.DataFrame(pesos)
ps

0          1          2          3          4          5  \
0  88.915623  84.894660  90.567574  68.272768  52.528435  77.026301   
1  98.606627  76.056414  73.103931  91.517314  62.969006  80.137302   
2  57.932216  85.848525  65.557838  58.205025  58.626151  60.732350   
3  90.006642  59.120421  66.261812  66.070342  59.120072  52.918555   
4  84.271430  70.684425  88.915951  48.965904  52.179928  84.632610   

           6          7          8          9  
0  53.963033  55.116583  76.576037  71.521936  
1  62.911527  96.871129  58.327790  58.730815  
2  40.353697  65.718603  60.354919  85.697854  
3  54.951106  42.300825  55.957011  95.030678  
4  46.870616  83.988306  49.914527  89.500474

In [0]:
al=pd.DataFrame(alturas)
al

0         1         2         3         4         5         6  \
0  1.100000  1.120408  1.140816  1.161224  1.181633  1.202041  1.222449   
1  1.304082  1.324490  1.344898  1.365306  1.385714  1.406122  1.426531   
2  1.508163  1.528571  1.548980  1.569388  1.589796  1.610204  1.630612   
3  1.712245  1.732653  1.753061  1.773469  1.793878  1.814286  1.834694   
4  1.916327  1.936735  1.957143  1.977551  1.997959  2.018367  2.038776   

          7         8         9  
0  1.242857  1.263265  1.283673  
1  1.446939  1.467347  1.487755  
2  1.651020  1.671429  1.691837  
3  1.855102  1.875510  1.895918  
4  2.059184  2.079592  2.100000

In [0]:
imc=pesos/(alturas**2)
imc

array([52.97526706, 49.75713756, 57.84281716, 51.43617988, 44.61178308,
       37.0375614 , 40.9779224 , 37.86327449, 61.34257651, 45.90668048,
       56.04920355, 27.73842452, 52.38179065, 26.89670888, 43.61370195,
       21.43753682, 43.18616398, 37.15203609, 39.08338149, 23.16275497,
       28.63306167, 26.98802912, 36.48210097, 33.64956591, 26.80835479,
       20.97083386, 19.12449191, 34.33401626, 26.95831135, 18.45765498,
       21.29964383, 17.94393886, 17.69233694, 24.56854538, 15.43258417,
       23.70164523, 16.73001336, 22.06360215, 25.50586284, 27.21260702,
       22.59986265, 23.97142073, 19.2887958 , 19.61457974, 24.89258184,
       11.39096765, 15.60177345,  9.92241771, 11.50054243, 21.13607646])

In [0]:
imc[imc < 18.5]

array([18.45765498, 17.94393886, 17.69233694, 15.43258417, 16.73001336,
       11.39096765, 15.60177345,  9.92241771, 11.50054243])

In [1]:
for i in imc:
    if (i <18.5):
        print("Magro demais")
    elif (i>18.5 and i<24.9):
        print("talkei")

NameError: ignored